classDiagram

class Library {
    add_book()
    register_user()
    create_loan()
}

class Book {
    title: str
    author: str
    state: bool
    mark_as_unavailable()
    mark_as_available()
}

class User {
    name: str
    email: str
}

class Loan {
    start_date: str
    end_date: str
    close_loan()
}

Library "1" --> "0..*" Book
Library "1" --> "0..*" User
Library "1" --> "0..*" Loan

User "1" --> "0..*" Loan
Book "1" --> "0..*" Loan