sequenceDiagram
participant User
participant Library
participant Book
User->> Library:create_loan()
Library->>Book:mark_as_unavailable()
create participant Loan
Library->> Loan:create_loan()
Library-->>User: loan created